### ISSUE TITLE
Overload Member methods

### ISSUE THREAD

**Issue by NeilKleistGao** [NeilKleistGao/ts-to-mls#36]
```ts
class M {
  foo(x: number): number;
  foo(x: string): string;

  foo(x) {
    return x;
  }
}
```

**Comment by NeilKleistGao** [comment]
```
[info] - Overload *** FAILED ***                                                                                                                    
[info]   scala.MatchError: (number) => number & ((string) => string) (of class ts2mls.types.TSIntersectionType)                                     
[info]   at ts2mls.TSSourceFile.getClassMembersType(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:29844:17)                
[info]   at ts2mls.TSSourceFile.parseMembers(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:29876:60)                       
[info]   at ts2mls.TSSourceFile.visit(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:29456:22)                              
[info]   at {anonymous}()(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:29945:5)                                           
[info]   at scala.scalajs.runtime.AnonFunction1.apply(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:35235:43)              
[info]   at scala.scalajs.js.Any$.fromFunction1(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:35180:25)                    
[info]   at visitNodes(/mnt/d/Code/ts-to-mls/node_modules/typescript/lib/typescript.js:30672:30)                                                    
[info]   at Object.forEachChild(/mnt/d/Code/ts-to-mls/node_modules/typescript/lib/typescript.js:30951:24)
[info]   at ts2mls.TypeScript$.forEachChild(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:19964:52)                        
[info]   at ts2mls.TSSourceFile.<init>(/mnt/d/Code/ts-to-mls/target/scala-2.13/ts-to-mls-test-fastopt/main.js:29944:28)                             
[info]   ... 
```
