### ISSUE TITLE
Array Intersection Runtime Error

### ISSUE THREAD

**Issue by NeilKleistGao** [NeilKleistGao/ts-to-mls#67]
```ts
function arr(a: number[] & string[]): number[] & string[] {
  return a;
}
```

leads to:
```
[info] - Intersection Declaration Generation *** FAILED ***                                                                                         
[info]   scala.scalajs.js.JavaScriptException: TypeError: Cannot read properties of undefined (reading 'valueDeclaration')                          
[info]   at ts2mls.TSTypeChecker.getTypeOfSymbolAtLocation(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:20022:150)        
[info]   at ts2mls.TSSymbolObject.getType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:30543:18)
[info]   at ts2mls.TSSourceFile.getObjectType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:29989:56)                      
[info]   at ts2mls.TSSourceFile.getIntersectionType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:30156:77)                
[info]   at ts2mls.TSSourceFile.getObjectType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:29975:17)                      
[info]   at ts2mls.TSSourceFile.getFunctionParametersType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:30084:16)          
[info]   at ts2mls.TSSourceFile.getFunctionType(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:30120:17)                    
[info]   at ts2mls.TSSourceFile.visit(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:29872:20)                              
[info]   at {anonymous}()(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:30459:5)                                           
[info]   at scala.scalajs.runtime.AnonFunction1.apply(/mnt/d/Code/ts-to-mls/js/target/scala-2.13/ts2mls-test-fastopt/main.js:35896:43)              
[info]   ...
```

**Comment by NeilKleistGao** [comment]
Same:
```ts
function tt(x: [string, number] & [boolean, boolean]): [string, number] & [boolean, boolean] {
  return x;
}
```

**Comment by NeilKleistGao** [comment]
Use this instead:
```ts
function arr<U, T>(a: U[] & T[]): U[] & T[] {
  return a;
}
```

**Comment by NeilKleistGao** [comment]
Use this instead:
```ts
function arr<U, T>(a: U[] & T[]): U[] & T[] {
  return a;
}
```
